In [23]:
import pandas as pd

In [24]:
host = 'hh-pgsql-public.ebi.ac.uk'
port = 5432
database = 'pfmegrnargs'
user = 'reader'
password = 'NWDMCE5xdipIjRrp'

In [25]:
import psycopg2

In [26]:
try:
    conn = psycopg2.connect(dbname=database, user=user, password=password, host=host)
except:
    print('Can`t establish connection to database')

In [27]:
with conn.cursor() as cursor:
    cursor.execute('SELECT * FROM rnc_database limit 10')
    rnc_database_10 = cursor.fetchall()

In [28]:
rnc_database_10 [:10]

[(21,
  datetime.datetime(2017, 5, 2, 0, 0),
  'RNACEN',
  'NONCODE',
  146,
  'NONCODE',
  'Y',
  ' ',
  'NONCODE',
  '',
  1130,
  201,
  244296,
  234669,
  7,
  'is an integrated knowledge database dedicated to non-coding RNAs',
  'http://www.noncode.org/',
  [{'upi': 'URS000019B796', 'taxid': 9606},
   {'upi': 'URS00008189E4', 'taxid': 9606},
   {'upi': 'URS000058E3EB', 'taxid': 9606}],
  [{'title': 'NONCODE 2016: an informative and valuable data source of long non-coding RNAs',
    'authors': 'Zhao Y, Li H, Fang S, Kang Y, Wu W, Hao Y, Li Z, Bu D, Sun N, Zhang MQ, Chen R',
    'journal': 'Nucleic Acids Res. 2016 Jan 4;44(D1):D203-8',
    'pubmed_id': '26586799'}]),
 (5,
  datetime.datetime(2017, 5, 17, 0, 0),
  'RNACEN',
  'VEGA',
  98,
  'VEGA',
  'N',
  ' ',
  'VEGA',
  'PRJEB4568',
  None,
  None,
  None,
  0,
  0,
  'is a repository for high-quality gene models produced by the manual annotation of vertebrate genomes. Human and mouse data from Vega are merged into <a href="http://www.gencodegenes.org/" target="_blank">GENCODE</a>',
  'http://vega.sanger.ac.uk/',
  [{'upi': 'URS00000B15DA', 'taxid': 9606},
   {'upi': 'URS00000A54A6', 'taxid': 9606},
   {'upi': 'URS0000301B08', 'taxid': 9606}],
  [{'title': 'The GENCODE v7 catalog of human long noncoding RNAs: analysis of their gene structure, evolution, and expression.',
    'authors': 'Derrien T., Johnson R., Bussotti G., Tanzer A., Djebali S., Tilgner H., Guernec G., Martin D., Merkel A., Knowles DG. et al.',
    'journal': 'Genome Res. 22(9): 1775-1789 (2012 Sep)',
    'pubmed_id': '22955988'},
   {'title': 'GENCODE: the reference human genome annotation for The ENCODE Project',
    'authors': 'Harrow J., Frankish A., Gonzalez JM., Tapanari E., Diekhans M., Kokocinski F., Aken BL., Barrell D., Zadissa A., Searle S. et al.',
    'journal': 'Genome Res. 22(9): 1760-1774 (2012 Sep)',
    'pubmed_id': '22955987'}]),
 (26,
  datetime.datetime(2017, 5, 1, 0, 0),
  'RNACEN',
  'GENCODE',
  450,
  'GENCODE',
  'N',
  ' ',
  'GENCODE',
  '',
  889,
  32,
  205012,
  47677,
  2,
  'produces high quality reference gene annotation and experimental validation for human and mouse genomes',
  'http://gencodegenes.org/',
  [{'upi': 'URS00000B15DA', 'taxid': 9606},
   {'upi': 'URS00000A54A6', 'taxid': 9606},
   {'upi': 'URS000078452D', 'taxid': 10090}],
  [{'title': 'GENCODE: the reference human genome annotation for The ENCODE Project',
    'authors': 'Harrow J, Frankish A, Gonzalez JM, Tapanari E, Diekhans M, Kokocinski F, Aken BL, Barrell D, Zadissa A et al.',
    'journal': 'Genome research 2012;22;9;1760-74',
    'pubmed_id': '22955987'}]),
 (1,
  datetime.datetime(2017, 5, 1, 0, 0),
  'RNACEN',
  'ENA',
  968,
  'ENA',
  'Y',
  ' ',
  'ENA',
  '',
  412,
  10,
  900074,
  12086180,
  814855,
  "provides a comprehensive record of the world's nucleotide sequencing information",
  'https://www.ebi.ac.uk/ena/browser/',
  [{'upi': 'URS00002D0E0C', 'taxid': 10090},
   {'upi': 'URS000035EE7E', 'taxid': 9606},
   {'upi': 'URS0000000001', 'taxid': 77133}],
  [{'title': 'The European Nucleotide Archive in 2017',
    'authors': 'Silvester et al.',
    'journal': 'Nucleic Acids Res. 2017',
    'pubmed_id': '29140475'}]),
 (14,
  datetime.datetime(2017, 5, 1, 0, 0),
  'RNACEN',
  'TAIR',
  982,
  'TAIR',
  'Y',
  ' ',
  'TAIR',
  'PRJ_TAIR',
  384,
  19,
  6227,
  4406,
  1,
  'is a database of genetic and molecular biology data for the model higher plant Arabidopsis thaliana',
  'http://www.arabidopsis.org/',
  [{'upi': 'URS0000591E4F', 'taxid': 3702},
   {'upi': 'URS000008172F', 'taxid': 3702},
   {'upi': 'URS000035F1B7', 'taxid': 3702}],
  [{'title': 'The Arabidopsis Information Resource (TAIR): improved gene annotation and new tools',
    'authors': 'Lamesch P., Berardini T.Z., Li D., Swarbreck D., Wilks C., Sasidharan R., Muller R., Dreher K., Alexander D.L., Garcia-Hernandez M., Karthikeyan A.S. et al.',
    'journal': 'Nucleic Acids Res. 2012 Jan;40(Database issue):D1202-10',
    'pubmed_id': '22140109'}]),
 (9,
  datetime.datetime(2017, 5, 1, 0, 0),
  'RNACEN',
  'REFSEQ',
  969,
  'RefSeq',
  'Y',
  ' ',
  'RefSeq',
  '',
  703,
  15,
  91667,
  120355,
  22524,
  'is a comprehensive, integrated, non-redundant, well-annotated set of reference sequences',
  'http://www.ncbi.nlm.nih.gov/refseq/',
  [{'upi': 'URS000075A3E5', 'taxid': 10090},
   {'upi': 'URS000075ADFF', 'taxid': 9606},
   {'upi': 'URS00003A96B7', 'taxid': 192222}],
  [{'title': 'RefSeq: an update on mammalian reference sequences.',
    'authors': 'Pruitt K.D., Brown G.R., Hiatt S.M., Thibaud-Nissen F., Astashyn A., Ermolaeva O., Farrell C.M., Hart J., Landrum M.J., McGarvey K.M. et al.',
    'journal': 'Nucleic Acids Res. 2014 Jan;42(Database issue):D756-63',
    'pubmed_id': '24259432'}]),
 (41,
  datetime.datetime(2017, 5, 1, 0, 0),
  'RNACEN',
  'GENECARDS',
  978,
  'MalaCards',
  'Y',
  ' ',
  'GeneCards',
  '',
  1292,
  16,
  347561,
  425357,
  1,
  'is a searchable, integrative database that provides comprehensive, user-friendly information on all annotated and predicted human genes',
  'https://www.genecards.org/',
  [{'upi': 'URS0000EBFCE3', 'taxid': 9606},
   {'upi': 'URS0000EBF55E', 'taxid': 9606},
   {'upi': 'URS0000EBF67F', 'taxid': 9606}],
  [{'title': 'The GeneCards Suite: From Gene Data Mining to Disease Genome Sequence Analyses',
    'authors': 'Stelzer G, Rosen N, Plaschkes I, Zimmerman S, Twik M, Fishilevich S, Stein T, Nudel R, Lieder I, Mazor Y, Kaplan S, Dahary D, Warshawsky D, Guan-Golan Y, Kohn A, Rappaport N, Safran M, Lancet D',
    'journal': 'Curr Protoc Bioinformatics. 2016 Jun 20;54:1.30.1-1.30.33',
    'pubmed_id': '27322403'}]),
 (10,
  datetime.datetime(2017, 5, 1, 0, 0),
  'RNACEN',
  'RDP',
  85,
  'RDP',
  'Y',
  ' ',
  'RDP',
  '',
  1536,
  1337,
  1600,
  4779,
  2487,
  'provides quality-controlled, aligned and annotated rRNA sequences and a suite of analysis tools',
  'http://rdp.cme.msu.edu/',
  [{'upi': 'URS0000434740', 'taxid': 338963},
   {'upi': 'URS000071C755', 'taxid': 224308},
   {'upi': 'URS0000090853', 'taxid': 637905}],
  [{'title': 'Ribosomal Database Project: data and tools for high throughput rRNA analysis',
    'authors': 'Cole J.R., Wang Q., Fish J.A., Chai B., McGarrell D.M., Sun Y., Brown C.T., Porras-Alfaro A., Kuske C.R., Tiedje J.M.',
    'journal': 'Nucleic Acids Res. 2014 Jan;42(Database issue):D633-42',
    'pubmed_id': '24288368'}]),
 (20,
  datetime.datetime(2017, 5, 1, 0, 0),
  'RNACEN',
  'LNCIPEDIA',
  935,
  'LNCipedia',
  'Y',
  ' ',
  'LNCipedia',
  '',
  1534,
  200,
  152544,
  126876,
  1,
  'is a comprehensive compendium of human long non-coding RNAs',
  'http://www.lncipedia.org/',
  [{'upi': 'URS000081175C', 'taxid': 9606},
   {'upi': 'URS0000812103', 'taxid': 9606},
   {'upi': 'URS00001F1863', 'taxid': 9606}],
  [{'title': 'An update on LNCipedia: a database for annotated human lncRNA sequences',
    'authors': 'Volders PJ, Verheggen K, Menschaert G, Vandepoele K, Martens L, Vandesompele J, Mestdagh P',
    'journal': 'Nucleic Acids Res. 2015 Jan;43(Database issue):D174-80',
    'pubmed_id': '25378313'}]),
 (15,
  datetime.datetime(2017, 5, 2, 0, 0),
  'RNACEN',
  'WORMBASE',
  970,
  'WormBase',
  'Y',
  ' ',
  'WormBase',
  'PRJNA13758',
  171,
  17,
  84141,
  25550,
  1,
  'curates, stores and displays genomic and genetic data about nematodes with primary emphasis on <em>C. elegans</em> and related nematodes',
  'http://www.wormbase.org/',
  [{'upi': 'URS000022A09E', 'taxid': 6239},
   {'upi': 'URS00001218EE', 'taxid': 6239},
   {'upi': 'URS00003E1CE3', 'taxid': 6239}],
  [{'title': 'WormBase 2012: more genomes, more data, new website',
    'authors': 'Yook K., Harris TW., Bieri T., Cabunoc A., Chan J., Chen WJ., Davis P., de la Cruz N., Duong A., Fang R. et al.',
    'journal': 'Nucleic Acids Res. 2012 Jan;40(Database issue):D735-41',
    'pubmed_id': '22067452'}])]

In [29]:
rnc_database_df = pd.DataFrame(rnc_database_10)
rnc_database_df.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,21,2017-05-02,RNACEN,NONCODE,146,NONCODE,Y,,NONCODE,,1130.0,201.0,244296.0,234669,7,is an integrated knowledge database dedicated ...,http://www.noncode.org/,"[{'upi': 'URS000019B796', 'taxid': 9606}, {'up...",[{'title': 'NONCODE 2016: an informative and v...
1,5,2017-05-17,RNACEN,VEGA,98,VEGA,N,,VEGA,PRJEB4568,NaN,NaN,NaN,0,0,is a repository for high-quality gene models p...,http://vega.sanger.ac.uk/,"[{'upi': 'URS00000B15DA', 'taxid': 9606}, {'up...",[{'title': 'The GENCODE v7 catalog of human lo...
2,26,2017-05-01,RNACEN,GENCODE,450,GENCODE,N,,GENCODE,,889.0,32.0,205012.0,47677,2,produces high quality reference gene annotatio...,http://gencodegenes.org/,"[{'upi': 'URS00000B15DA', 'taxid': 9606}, {'up...",[{'title': 'GENCODE: the reference human genom...
3,1,2017-05-01,RNACEN,ENA,968,ENA,Y,,ENA,,412.0,10.0,900074.0,12086180,814855,provides a comprehensive record of the world's...,https://www.ebi.ac.uk/ena/browser/,"[{'upi': 'URS00002D0E0C', 'taxid': 10090}, {'u...",[{'title': 'The European Nucleotide Archive in...
4,14,2017-05-01,RNACEN,TAIR,982,TAIR,Y,,TAIR,PRJ_TAIR,384.0,19.0,6227.0,4406,1,is a database of genetic and molecular biology...,http://www.arabidopsis.org/,"[{'upi': 'URS0000591E4F', 'taxid': 3702}, {'up...",[{'title': 'The Arabidopsis Information Resour...
5,9,2017-05-01,RNACEN,REFSEQ,969,RefSeq,Y,,RefSeq,,703.0,15.0,91667.0,120355,22524,"is a comprehensive, integrated, non-redundant,...",http://www.ncbi.nlm.nih.gov/refseq/,"[{'upi': 'URS000075A3E5', 'taxid': 10090}, {'u...",[{'title': 'RefSeq: an update on mammalian ref...
6,41,2017-05-01,RNACEN,GENECARDS,978,MalaCards,Y,,GeneCards,,1292.0,16.0,347561.0,425357,1,"is a searchable, integrative database that pro...",https://www.genecards.org/,"[{'upi': 'URS0000EBFCE3', 'taxid': 9606}, {'up...",[{'title': 'The GeneCards Suite: From Gene Dat...
7,10,2017-05-01,RNACEN,RDP,85,RDP,Y,,RDP,,1536.0,1337.0,1600.0,4779,2487,"provides quality-controlled, aligned and annot...",http://rdp.cme.msu.edu/,"[{'upi': 'URS0000434740', 'taxid': 338963}, {'...",[{'title': 'Ribosomal Database Project: data a...
8,20,2017-05-01,RNACEN,LNCIPEDIA,935,LNCipedia,Y,,LNCipedia,,1534.0,200.0,152544.0,126876,1,is a comprehensive compendium of human long no...,http://www.lncipedia.org/,"[{'upi': 'URS000081175C', 'taxid': 9606}, {'up...",[{'title': 'An update on LNCipedia: a database...
9,15,2017-05-02,RNACEN,WORMBASE,970,WormBase,Y,,WormBase,PRJNA13758,171.0,17.0,84141.0,25550,1,"curates, stores and displays genomic and genet...",http://www.wormbase.org/,"[{'upi': 'URS000022A09E', 'taxid': 6239}, {'up...","[{'title': 'WormBase 2012: more genomes, more ..."

In [30]:
with conn.cursor() as cursor:
    cursor.execute('SELECT display_name, num_sequences, num_organisms, url FROM rnc_database limit 10')
    rnc_database_1 = cursor.fetchall()

In [31]:
rnc_database_1 [:10]

[('NONCODE', 234669, 7, 'http://www.noncode.org/'),
 ('VEGA', 0, 0, 'http://vega.sanger.ac.uk/'),
 ('GENCODE', 47677, 2, 'http://gencodegenes.org/'),
 ('ENA', 12086180, 814855, 'https://www.ebi.ac.uk/ena/browser/'),
 ('TAIR', 4406, 1, 'http://www.arabidopsis.org/'),
 ('RefSeq', 120355, 22524, 'http://www.ncbi.nlm.nih.gov/refseq/'),
 ('GeneCards', 425357, 1, 'https://www.genecards.org/'),
 ('RDP', 4779, 2487, 'http://rdp.cme.msu.edu/'),
 ('LNCipedia', 126876, 1, 'http://www.lncipedia.org/'),
 ('WormBase', 25550, 1, 'http://www.wormbase.org/')]

In [33]:
rnc_database_1_df = pd.DataFrame(rnc_database_1)
rnc_database_1_df.head(10)

           0         1       2                                    3
0    NONCODE    234669       7              http://www.noncode.org/
1       VEGA         0       0            http://vega.sanger.ac.uk/
2    GENCODE     47677       2             http://gencodegenes.org/
3        ENA  12086180  814855   https://www.ebi.ac.uk/ena/browser/
4       TAIR      4406       1          http://www.arabidopsis.org/
5     RefSeq    120355   22524  http://www.ncbi.nlm.nih.gov/refseq/
6  GeneCards    425357       1           https://www.genecards.org/
7        RDP      4779    2487              http://rdp.cme.msu.edu/
8  LNCipedia    126876       1            http://www.lncipedia.org/
9   WormBase     25550       1             http://www.wormbase.org/